name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'hotfix/**'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run Test
        run: go test -v ./...
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run Build
        run: go build -v ./...
  version:
    name: Version Runner
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x
          preferLatestVersion: true
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Display Version
        run: |
          echo "Version: v${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.branchName }}"
